# Project information
site_name: OWASP Cheat Sheet Series
site_url: https://cheatsheetseries.owasp.org/
site_description: Website with the collection of all the cheat sheets of the project.
# Repository
repo_name: OWASP/CheatSheetSeries
repo_url: https://github.com/OWASP/CheatSheetSeries
edit_uri: ""

# Copyright
copyright: Â©Copyright 2021 - CheatSheets Series Team - This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.

#Config
docs_dir: cheatsheets/
google_analytics:
  - !!python/object/apply:os.getenv ["WORKFLOW_GOOGLE_ANALYTICS_KEY", "none"]
  - auto
use_directory_urls: false
plugins:
  - search:
    #        prebuild_index: true
      lang:
        - en
#For read the docs
# theme:
#     name: readthedocs
#     custom_dir: custom_theme/
#     highlightjs: true
#     sticky_navigation: false
# markdown_extensions:
#     - pymdownx.emoji:
#        emoji_index: !!python/name:pymdownx.emoji.twemoji
#        emoji_generator: !!python/name:pymdownx.emoji.to_alt
#     - toc:
#         permalink: true

#For material
theme:
  name: material
  custom_dir: custom_theme/
  favicon: assets/WebSite_Favicon.png
  logo: "assets/OWASP_Logo_Transp.png"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences # Required by Pygments
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: true
